#!/bin/bash
echo -e -n "\e[0;33mWelcome to HathoutDB v.1\n"
echo -e -n "\e[0;33m**You can use MongoDB commands for HathoutDB**\n"
echo -e -n "\e[0;31m**For more info:"
echo -e -n "\e[0;32m \$man HathoutDB\n"

# echo -e -n "\e[0;32mHathoutDB>"
# read cmd
cmd=0
currentdb=''


while [[ $cmd != $EOF ]]
do
	echo -e -n "\e[0;32mHathoutDB>"
	read cmd
	if [[ $cmd == "man HathoutDB" ]]; then
			echo "Man page"

####################################DEALING WITH DATABASES######################################
#use dbName: for opening a db or creating a new db if not exist
	elif [[ $cmd =~ ^use.[a-z|A-Z]+ ]]; then
			dbName="${cmd//use /}"
			./createdbs $dbName
			currentdb=$dbName

#showing dbs: to list all db names
	elif [[ $cmd == "show dbs" ]]; then
			./createdbs $cmd

#current db(): To specify the currently used db
	elif [[ $cmd == "current db()" ]]; then
			echo $currentdb

#db.dropDatabase(): Drop a database that is currently in use "You have to make use dbName before using it"
	elif [[ $cmd == "db.dropDatabase()" ]]; then
			if [[ !  -z  $currentdb ]]; then
						./createdbs $cmd $currentdb
						currentdb=''
			else
						echo "You should type \$ use dbName before dropping"
			fi
#########################################End DEALING WIH DATABSES##############################################

#######################################Dealing with Collections################################

# db.createCollection(name): For creating collection.
elif [[ $cmd =~ ^db.createCollection\(.+\) ]]; then
			colNametemp="${cmd//db.createCollection\(/}"
			colName="${colNametemp//\)/}"
			if [[ !  -z  $currentdb ]]; then
						./createCollections create $currentdb $colName
			else
						echo "You should type \$ use dbName before creating a collection"
		  fi

#show collections: To list all collection names
elif [[ $cmd == "show collections" ]]; then
			if [[ !  -z  $currentdb ]]; then
						./createCollections show $currentdb
			else
						echo "You should type \$ use dbName before creating a collection"
		  fi

#db.collection.drop(): to remove a collection
elif [[ $cmd =~ ^db.+drop\(\) ]]; then
			colNameStart="${cmd//db./}"
			colName="${colNameStart//.drop()/}"
			if [[ !  -z  $currentdb ]]; then
						./createCollections drop $currentdb $colName
			else
						echo "You should type \$ use dbName before creating a collection"
		  fi


	elif [[ $cmd == $EOF ]]; then
			echo -e -n "\e[0;31mThank you for using HathoutDB\n"
	else
			echo -e -n "\e[0;31mNot a HathoutDB command\n"
	fi

#########################################End DEALING WIH collections##############################################

#######################################Dealing with Documents################################

done
echo "Bye Bye"
