#!/bin/bash

#Create: creating a table if not exist
if [[ $1 == "create" ]]; then
    if [ ! -f "../dbs/$2/$3" ]; then
      touch ../dbs/$2/$3
      echo "Table $3 created"
    else
      echo "Table $3 already exist"
    fi

#To list all collections
elif [[ $1 == "show" ]]; then
    for i in $(ls -f ../dbs/$2*/); do echo ${i%%/}; done

elif [[ $1 == "drop" ]]; then
    if [ ! -f "../dbs/$2/$3" ]; then
          echo "There is no table $3 "
    else
          rm ../dbs/$2/$3
          echo "Table $3 dropped"
    fi

fi







#
# # #Creating a db 'directory' if not exist
#
# #To list all dbs
# if [[ $1 == "show" ]]; then
#   for i in $(ls -d ../dbs/*/); do echo ${i%%/}; done
#
#
# #To drop a db is exist
# elif [[ $1 == "db.dropDatabase()" ]]; then
#     if [ ! -d "../dbs/$2" ]; then
#         echo "There is no db $2 exist"
#     else
#         rm -r ../dbs/$2
#         echo "$2 db dropped.."
#     fi
#
# #To create new db if not exit already
# else
#     if [ ! -d "../dbs/$1" ]; then
#       echo "Creating New db $1"
#       mkdir ../dbs/$1
#       echo "Switching to $1 db.."
#     else
#       echo "Switching to $1 db.."
#     fi
# fi
