#!/bin/bash


# Stracturing the table
if [[ -f "../dbs/$1/$2" ]]; then
    ensuringDataFlag=true
    while $ensuringDataFlag; do
      echo ">How many columns in table $2 you want?"
      read numOfColums
      if [[ "$numOfColums" = +([1-9])*([0-9]) ]]; then
        ensuringDataFlag=false
      else
        echo "Invalid entry"
      fi
    done
    flag31=true
    while $flag31; do
      echo
      echo ">Enter PK name:"
      read pk_name
      if ! [[ "$pk_name" = '' ]]; then
        echo -n "$pk_name" >> "../dbs/$1/$2"
        echo -n "-" >> "../dbs/$1/$2"
        flag31=false
      else
        echo "Invalid entry"
      fi
    done
    flag31=true
    while $flag31; do
      echo "Enter PK datatype: "
      select choice in "Integer" "String"; do
        if [[ "$REPLY" = "1" || "$REPLY" = "2" ]]; then
          echo -n "$choice" >> "../dbs/$1/$2"
          echo -n "-" >> "../dbs/$1/$2"
          flag31=false
        else
          echo "Invalid entry"
        fi
        break
      done
    done
    flag31=true
    while $flag31; do
      echo "Enter column size: "
      read size
      if [[ "$size" = +([1-9])*([0-9]) ]]; then
        echo -n "$size" >> "../dbs/$1/$2"
        echo -n ":" >> "../dbs/$1/$2"
        flag31=false
      else
        echo "Invalid entry"
      fi
    done
    for (( i = 1; i < numOfColums; i++ )); do
      flag31=true
      while $flag31; do
        echo
        echo Enter field $[i+1] name:
        read pk_name
        if ! [[ "$pk_name" = '' ]]; then
          echo -n "$pk_name" >> "../dbs/$1/$2"
          echo -n "-" >> "../dbs/$1/$2"
          flag31=false
        else
          echo "Invalid entry"
        fi
      done
      flag31=true
      while $flag31; do
        echo Enter field $[i+1] datatype:
        select choice in "Integer" "String"; do
          if [[ "$REPLY" = "1" || "$REPLY" = "2" ]]; then
            echo -n "$choice" >> "../dbs/$1/$2"
            echo -n "-" >> "../dbs/$1/$2"
            flag31=false
          else
            echo "Invalid entry"
          fi
          break
        done
      done
      flag31=true
      while $flag31; do
        echo ">Enter field $[i+1] size:"
        read size
        if [[ "$size" = +([1-9])*([0-9]) ]]; then
          echo -n "$size" >> "../dbs/$1/$2"
          if [[ i -eq $numOfColums-1 ]]; then
            echo $'\n' >> "../dbs/$1/$2"
            echo ">Table $2 stracture is created successfully"
            echo "Press any key to continue .."
            read
          else
            echo -n ":" >> "../dbs/$1/$2"
          fi
          flag31=false
        else
          echo "Invalid entry"
        fi
      done
    done
  else
    echo "Invalid entry"
    echo "Press any key to continue .."
    read
fi
